# Site settings
title: 平安喜乐
header-img: "img/autumn2.jpg"
tagline: "吉光片羽"  
description: "慢慢来，面包会有的，比面包更好吃的面包也会有的"  
baseurl: ""
<<<<<<< HEAD
url: "http://jenniferhe.github.io"  
#url: "http://localhost:4000"
=======
url: "http://jenn001.com"  
>>>>>>> origin/master

# About/contact
owner: 
  name: "Jennifer He"
  email: yuxuan.he@richmond.edu
<<<<<<< HEAD
  bio: "我不是一个没有故事的女同学~"
=======
  bio: "明朝即長路 惜取此時心"
>>>>>>> origin/master

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: 阿和盒子
<<<<<<< HEAD
#twitter_username: Azeril_Lapland  
github_username: jenniferhe  
facebook_username: jennifer he  
#weibo_username: Azeril  
zhihu_username: 阿和盒子  
=======
# twitter_username: Azeril_Lapland  
github_username: jenniferhe  
facebook_username: jennifer he 
#weibo_username: Azeril  
#zhihu_username:   
>>>>>>> origin/master

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jennifer"
<<<<<<< HEAD
      header-img: "img/tree.jpg" # We don't want posts without a header image, that whould mean white on white
=======
      header-img: "img/autumn.jpg" # We don't want posts without a header image, that whould mean white on white
>>>>>>> origin/master


# Comments 
comments :
  provider : duoshuo
  duoshuo :
<<<<<<< HEAD
    short_name : Jennifer
  disqus :
      short_name : Jennifer
=======
    short_name : Jenniferhe
  disqus :
      short_name : Jenniferhe
>>>>>>> origin/master

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
